### ISSUE TITLE
master password required when using keyfile

### ISSUE THREAD

**Issue by dkebler** [OneKeePass/desktop#10]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

master password required when using keyfile

### What software is involved?

- Operating System:  linux, arch, manjaro
- OneKeePass:  latest
- …

Long time keepass user here both keepass (mono)  and keepassxc.
I have a database that uses a keyfile (and only a keyfile).  Your implementation does not support this (mobile too)  so I am unable to open my databases.  Thus I can't even evaluate onekeepass.  Was this intentional?  Are there plans to support this?  If not that would preclude many users including myself.

### Steps to Reproduce

Ask to open database with a key file.  Choose keyfile.  Program  indicates that a valid password is required.

### Expected Behavior

database opens

### Actual Behavior

asks for a valid password.

### Reproducibility

Always

**Comment by jeyasankar** [comment]
Hi @dkebler ,

Thanks taking time to check OneKeePass. I assumed many users will be using mostly password and optionally key file. You are correct that both Keepass and KeepassXC support the key file only use to open the database. I will make changes to use only key file if user desired so in the next release. Hopefully you will be able to use then with your database

**Comment by dkebler** [comment]
Thx!,  Always looking to use a better UI with my keepass databases.   I've segued  to XC  for that reason and was happy to see you are actively working on this

FYI, my use case.

For a long time I used just a strong password.  Just got tried of typing it.  I did not want to go the route of a yubi key etc so I use a keyfile now  on a usb stick and that works well and avoids having to type a password.  Further since I use more than one database I use a single "opener" database with that key file and that uses "autoopen"  to open my actual databases that have super strong master passwords.

autoopen is supported as a plugin with keepass and natively with keypassxc.  I'm suggesting that autoopen is important enough feature for "power users" that you should include it like keepassxc did.   I'd make sure it supports relative paths as when for instance I use the keypass databases on my phone the autoopen will "break" if it has absolute paths in the autoopen entries.  The other feature built in to XC is communicating with ssh-agent.  It works but is not as good as the keyagent plugin for keepass mono.  That is also a "power user" feature but is critical for my use case as I need my password manager to manage all my ssh keys and passphrases to keep them secure.

One thing I gave up moving from mono version to XC was a way to sync two copies of a database.  This has always been a pain.  To do that one had to keep primary copy use that to "sync" with a "transfer copy" then use a cloud (e.g. nextcloud) to move that to another device then run the "sync" from the transfer copy to the local copy on that other device.   It worked but sharing a copy of a database with someone else who might be making edits was not a foolproof especiallly  if the cloud gets confused about which is the "good" copy of the transfer database.  I have really not sure if there is a good solution considering keepass is not a db server with record locking but more like sqlite a stand alone file.

If I was a clojure/rust programmer I'd be in a better position to help out.  :(

**Comment by dkebler** [comment]
this is for bitwarden but it's written in Rust and talks to ssh agent so might be useful to you.

https://github.com/haipengno1/bw-key

**Comment by dkebler** [comment]
without opening another issue ...

another suggestion is to enable "discussion" for this repo so you won't end up with a bunch of noise (like this issue) in your issues.  Also will make it easy for user to user support.

Finally I might be able to help out writing that critical browser extension as that's going to be mostly in javascript.  Likewise you'll also want a way to insert fields in android like keepass2android can with its own android keyboard.

**Comment by jeyasankar** [comment]
Hi @dkebler ,

I have implemented one of your suggestion - using only the key file without password for the database master key. The latest release (Version 0.9.0)  of the App for all platform has this feature. Please have a look 

In coming releases, I will try to incorporate few more of your other suggestions.

Thanks

**Comment by dkebler** [comment]
Thanks!  

I will check it out after holidays.   I don't know if the mobile app now supports this but of course it should if the desktop app does.

With that in place I can do an honest comparison to keepassxc especially since keepassxc does not have a companion mobile app.

BTW Since I mentioned the autoopen feature as important I have discovered on linux machines that support dbus I can write scripts that auto open any database (using a keyfile on a stick).   This has allowed me to drop autoopen and move my three databases all to using keys, too given autoopen as it currently is coded doesn't support opening another database by keyfile (only password)

Assuming onekeepass command line supports passing the keyfile then the script suitably edited should work for onekeepass too.  That means at least for me (linux users) autoopen is no longer critical/needed.

```bash
#!/bin/bash
# Get password using secret-tool and unlock keepassxc
#  this currently only works for no password but key only unlock
database=${1:-$KEEPASS_DB_PATH}
keyfile=${2:-$KEEPASS_DB_KEY_PATH}
unlock="dbus-send --print-reply --dest=org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.KeePassXC.MainWindow.openDatabase string:$database string:"" string:$keyfile"
if ! qdbus | grep keepassxc; then 
  keepassxc& 
  sleep 1 
  if ! qdbus | grep keepassxc; then echo unable to start keepassxc; exit; fi
fi 
if $unlock  &> /dev/null; then
    echo keepass database $database succesfully unlocked   
  else
   echo unable to unlock $database
fi
```

Further I can open a separate (enhancement) issue about how to merge/sync two databases rather than discuss here in this closed database.   I do have some implementation ideas as regards this given my experience using "sync" with the original mono keepass.   

My other suggestion is to enable "discussion" on at least one of your repos.  I find it gives users a place to ask questions, suggest enhancements, and vet issues about the project without resorting to cluttering up the issue tracker.

**Comment by dkebler** [comment]
Little help.  I can't open my current kdbx because of wrong algorithm
`Only Argon 2d kdf algorithm is supported`

in keepassxc  

for Encryption Algorithm
my choices are
* AES 256  (current)
* twofish
* chacha20

and for key derivation function

* Argon 2d  (current)
* Argon 2id
*  AES-KDF

so as you can see these choices are not lining up with a single choice `Argon 2d kdf` so what do I conver to?

please elaborate.

**Comment by dkebler** [comment]
I got the right choice

just choose chach20  with keeping Argon 2d  works

**Comment by jeyasankar** [comment]
Hi @dkebler ,

As you have noted, OneKeePass supports only the following encryption algorithms and key derivation function (KDF) now:
AES 256
Chacha20

KDF:
Argon 2d

Support for other algorithms and kdf will be added in the future
