### ISSUE TITLE
Fedora support

### ISSUE THREAD

**Issue by nemke** [OneKeePass/desktop#19]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Support Fedora and all other Linux operating systems that use rpm

### Motivation

Was looking for an alternative for KeePass, since it's not longer possible to install it on Fedora few versions back. Found KeepassXC and few others but they do not provide option to use remote sync. They all say sync file yourself or use cloud sync software, which is valid, because you can now mount Google Drive inside Fedora very easily.

Thing is, and this is my assumption, a lot of us don't won't to keep password file on similar cloud based systems and like to host it our self.

**Comment by jeyasankar** [comment]
Thanks @nemke.  I need to do figure out the rpm packaging of a Tauri app. Hopefully it should be possible.

**Comment by LFd3v** [comment]
I do not mean to disturb any of you, but:

1. The AppImage version should work on Fedora, right?
2. There is a [deb to rpm tool](https://www.tecmint.com/convert-from-rpm-to-deb-and-deb-to-rpm-package-using-alien/) that may work (depending on how .deb was packaged, dependencies, etc).

Cheers

**Comment by jeyasankar** [comment]
Thanks @LFd3v .

Yes AppImage should on different Linux distributions and so it will work on Fedora also
The downloaded file needs to have an executable permission set

@nemke  Please use the AppImage distribution of the app  and I hope you will be able to use Google Drive with this
