### ISSUE TITLE
groups are lost when moving from keepassxc to onekeepass

### ISSUE THREAD

**Issue by dkebler** [OneKeePass/desktop#20]
If I open my database in onekeepass  my groups are gone (entries no longer organized by groups) and the `new group`  group menu option is greyed out.

If I open the same database in keepassxc (which I use now).  Not a problem.

Also,  do you not have a browser integration (way to inject credentials into browser fields)?

**Comment by jeyasankar** [comment]
Hi @dkebler ,

To see entries under groups, please select the option "Groups" as shown in the picture

<img width="448" alt="sample1" src="https://github.com/OneKeePass/desktop/assets/5703262/5f292ce3-8f67-4d90-b22d-75e1e640a5fc">
