### ISSUE TITLE
Need dark mode and add-ons for browser

### ISSUE THREAD

**Issue by shenzero123** [OneKeePass/desktop#24]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I need dark mode and add-ons for browser

### Motivation

I feel light mode made my eyes exploded, and it dont have extensions/add-ons for browser so it made me feel very disappointed.

**Comment by jeyasankar** [comment]
Hi @shenzero123 ,

Thanks for the suggestion. This feature - dark/light mode selection - will be added in a future release. The browser extension works will be done a little later

**Comment by jeyasankar** [comment]
Hi @shenzero123,

The release 0.13.0 has now dark/light mode selection
