### ISSUE TITLE
Since version 0.14.0, the database no longer opens

### ISSUE THREAD

**Issue by franco27** [OneKeePass/desktop#32]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After entering the password, the software closes.

### What software is involved?

64-bit operating system, x64 processor  
8.00 GB RAM  
AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G , 2.50 GHz  
Windows 10 Home

And
OnekeePass v0.14.0

### Steps to Reproduce

Hello

I didn't have this opening problem with previous versions,
OnekeePass v0.12.0
OnekeePass v0.13.0
I had to reinstall version 0.13.0.

1. I click on the icon and the software opens, I click on the database, recently opened.
I tried to open it with the Windows file explorer (by searching for the database).
2. The selected database, I enter the password.
3. I click on the button to validate, and the software shuts down.
4. No error message.

I uninstalled and reinstalled version 0.14.0 which did not solve this problem. Before the update, OnekeePass v0.13.0 was installed.

I installed version 0.13.0 again, and after selecting the database and entering the password, the database opens correctly.

### Expected Behavior

Normally the database should open.

### Actual Behavior

The software closes.

### Reproducibility

Always

**Comment by jeyasankar** [comment]
Hi @franco27 ,

Thanks for checking this version.

It seems the GitHub Action based build will work only with the latest Window OS. So I need to use a Windows 10 machine to build this release. 

Luckily I could build locally in my Windows 10 laptop. I have uploaded the same and you can download from the [release](https://github.com/OneKeePass/desktop/releases) again.  This should work in Windows 10 and 11. 

Please let me know if there is any issue
