### ISSUE TITLE
Groups menu is empty

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/desktop#5]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Groups menu shows no options when clicked.

### What software is involved?

- Operating System: Debian Linux - Testing
- OneKeePass: OneKeePass_0.7.0_linux_x86_64.AppImage

### Steps to Reproduce

1. Download and run OneKeePass 0.7.0 AppImage on Linux. 
2. Create or open a new KeePass database. 
3. Click on the **Groups** menu along the top of the Window. 
4. A blank menu appears with no selectable options. 

### Expected Behavior

Clicking the Groups menu should provide options to: 
1. Create Group
2. Edit
3. Sort
4. etc. 

### Actual Behavior

No options are displayed. 

### Reproducibility

Always

**Comment by jeyasankar** [comment]
Thanks gregordinary. I will take a look. I need to do more works on those menus as they are not yet complete

**Comment by jeyasankar** [comment]
Fixed in Release 0.8.0
