### ISSUE TITLE
Password Generator Does Not Save Generated Value to Entry

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/desktop#6]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When using the password generator, there is only a "Close" button which does not save or pass the generated password to the entry. 

### What software is involved?

- Operating System: Debian Linux - Testing (kernel 6.4.0-1)
- OneKeePass: OneKeePass_0.7.0_linux_x86_64.AppImage

### Steps to Reproduce

1. Open OneKeePass 0.7.0 AppImage on Linux
2. Open or Create a Keepass DB
3. Create or Edit an entry
4. On the **Password** field for an entry, click the 🗘 icon to open the Password Generator.
5. Generate a password of the desired length and complexity. 
6. Click **Close** (only visible option)
7. The Password field on the main entry will contain whatever was there previously (blank or old value)

### Expected Behavior

The password field in the entry should be populated with the generated value. I suggest via a Save button. The "Close" button can remain with its current behavior as a user might choose to back out of password generation.

### Actual Behavior

Generated passwords are not populated into an entry. 

### Reproducibility

Always

**Comment by gregordinary** [comment]
Hi @jeyasankar, I'm excited for your work on OneKeePass. I submitted this and a few other issues in the Desktop & Mobile repos. I am happy to help test builds, provide more details, etc. on issues I or others have submitted. Thank you for all the work you've put in to this!

**Comment by jeyasankar** [comment]
Hi @gregordinary . I saw all your your testing and tickets.  Thanks for taking time to use the apps and bringing to my attention any issues. I will be addressing all issues in the future releases and hope the apps will be useful without much of bugs or issues!. 
Thanks again for your help.

**Comment by jeyasankar** [comment]
Fixed in Release 0.8.0
