### ISSUE TITLE
Password strength indicator does not update on password edit field. 

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/desktop#7]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When editing the password field on an entry, the password strength indicator stays on "Very Dangerous"

### What software is involved?

- Operating System: Debian Linux - Testing (kernel 6.4.0-1)
- OneKeePass: OneKeePass_0.7.0_linux_x86_64.AppImage

### Steps to Reproduce

1. Open OneKeePass 0.7.0 AppImage on Linux
2. Open or Create a Keepass DB
3. Create or Edit an entry
4. On the Password field for an entry, type a password of any complexity. 
5. The text beneath the password field says "very dangerous" and will not change no matter how complex the password. 

### Expected Behavior

The complexity indicator should change as the user types or generates a password of varying complexity. 

### Actual Behavior

Complexity indicator always reads "Very Dangerous". 

### Reproducibility

Always

### Anything else?

![image](https://github.com/OneKeePass/desktop/assets/33880035/1a53737d-1ec5-4bdd-9581-0a58329196e5)

While the password strength indicator does not update on the password field editor, it *does* update on the password generator: 

![image](https://github.com/OneKeePass/desktop/assets/33880035/e9abe9fc-b480-4828-951d-235a5e1a1c5d)

**Comment by jeyasankar** [comment]
Thanks @gregordinary. I will fix this

**Comment by jeyasankar** [comment]
Fixed in Release 0.8.0
