### ISSUE TITLE
Error when attempting to clear password length in the password generator

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/desktop#8]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When using text entry to specify password length, trying to backspace over the first character results in "invalid args `passwordOptions` for command `analyzed_password`: invalid type: null, expected usize"

### What software is involved?

- Operating System: Debian Linux - Testing (kernel 6.4.0-1)
- OneKeePass: OneKeePass_0.7.0_linux_x86_64.AppImage

### Steps to Reproduce

1. Open OneKeePass 0.7.0 AppImage on Linux
2. Open or Create a Keepass DB
3. Create or Edit an entry
4. On the Password field for an entry, click the 🗘 icon to open the Password Generator.
5. Click into the text box where the password length is specified.
6. Select all text in the Password Length text box. 
7. Press Backspace or Delete on your keyboard
8. The following Error appears: `invalid args passwordOptions for command analyzed_password: invalid type: null, expected usize`
9. Pressing backspace again will allow clearing of the box to type in a new value. 

### Expected Behavior

1. Pressing backspace should remove the preceding character or clear the selected text.
2. A user-friendly warning should be returned for empty password lengths e.g., "password length cannot be 0"

### Actual Behavior

1. Attempting to remove all characters from the password length box results in the unfriendly error `invalid args passwordOptions for command analyzed_password: invalid type: null, expected usize`
2. Pressing backspace again will allow clearing and editing. 

### Reproducibility

Always

### Anything else?

![image](https://github.com/OneKeePass/desktop/assets/33880035/f8e71007-3941-4fa8-831b-b87ecbd4dcb8)

**Comment by jeyasankar** [comment]
Thanks @gregordinary. I will fix this

**Comment by jeyasankar** [comment]
Fixed in Release 0.8.0
