### ISSUE TITLE
Text boxes lack left and right padding

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/desktop#9]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/desktop/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/desktop/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Text input boxes are missing left & right padding resulting in icon overlap and decreased readability.

### What software is involved?

- Operating System: Debian Linux - Testing (kernel 6.4.0-1)
- OneKeePass: OneKeePass_0.7.0_linux_x86_64.AppImage

### Steps to Reproduce

1. Open OneKeePass database.
2. Add or edit an entry (Any action that brings up a text entry field will suffice).
3. Begin to type in a text box, the text starts right at the border of the field, without padding. 

1. Open OneKeePass database
2. Click to view an existing entry
3. Note the icons to copy, overlap with the right-edge of text fields. 

### Expected Behavior

Text entry should have padding and begin slightly indented form the border of a text box. Icons should not overlap with the borders of text boxes. 

### Actual Behavior

Text _nearly_ overlaps with the left side of a text box; icons overlap _slightly_ with the right edge of text-boxes.

### Reproducibility

Always

### Anything else?

Sample text without padding-left:
![image](https://github.com/OneKeePass/desktop/assets/33880035/4be8b47d-1a48-4f76-89a6-fa57b07a92cd)

Screenshot showing icons, e.g., copy icon, overlapping with the right edge of a text box: 
![image](https://github.com/OneKeePass/desktop/assets/33880035/f78cd9c1-6d1c-403f-9dce-4f39668e9358)

**Comment by jeyasankar** [comment]
Thanks @gregordinary. I will fix this. UI alignment issue I think

**Comment by jeyasankar** [comment]
Fixed in Release 0.8.0
